import os
import datetime
import matplotlib.pyplot as plt
from typing import Dict, Any, List
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, PageBreak, KeepTogether
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas

# Define theme colors
PRIMARY_COLOR = colors.HexColor("#4f46e5") # Indigo/Violet
SECONDARY_COLOR = colors.HexColor("#6366f1")
TEXT_COLOR = colors.HexColor("#1f2937") # Gray 800
LIGHT_BG = colors.HexColor("#f9fafb") # Gray 50
BORDER_COLOR = colors.HexColor("#e5e7eb") # Gray 200

# Risk-specific colors
RED_COLOR = colors.HexColor("#ef4444")
ORANGE_COLOR = colors.HexColor("#f59e0b")
GREEN_COLOR = colors.HexColor("#10b981")
BLUE_COLOR = colors.HexColor("#3b82f6")

class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas to calculate total page count and add professional header/footer.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        if self._pageNumber == 1:
            # Skip page decorations on the cover page
            return
            
        self.saveState()
        self.setFont("Helvetica", 9)
        self.setFillColor(colors.HexColor("#4b5563")) # Gray 600
        
        # Header (Top margin is 54pt, letter height is 792pt)
        self.drawString(54, 750, "AI Contract Analysis Report")
        self.setStrokeColor(BORDER_COLOR)
        self.setLineWidth(0.5)
        self.line(54, 742, 558, 742)
        
        # Footer
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(558, 40, page_text)
        self.drawString(54, 40, "Confidential - Generated by AI Contract Analyzer")
        self.line(54, 52, 558, 52)
        
        self.restoreState()

def generate_risk_chart(risky_clauses: List[Dict[str, Any]], output_path: str) -> bool:
    """
    Generates a donut risk breakdown chart and saves it as a PNG.
    """
    levels = {"High": 0, "Medium": 0, "Low": 0}
    for rc in risky_clauses:
        level = rc.get("risk_level", "Low").title()
        if level in levels:
            levels[level] += 1
        else:
            levels["Low"] += 1
            
    labels = list(levels.keys())
    sizes = list(levels.values())
    
    total = sum(sizes)
    if total == 0:
        sizes = [1]
        labels = ["No Risks Found"]
        chart_colors = ["#10b981"]
    else:
        chart_colors = ["#ef4444", "#f59e0b", "#10b981"]
        # Filter out slices with size 0
        filtered = [(l, s, c) for l, s, c in zip(labels, sizes, chart_colors) if s > 0]
        labels = [x[0] for x in filtered]
        sizes = [x[1] for x in filtered]
        chart_colors = [x[2] for x in filtered]
        
    try:
        fig, ax = plt.subplots(figsize=(3, 3))
        wedges, texts, autotexts = ax.pie(
            sizes,
            labels=labels,
            colors=chart_colors,
            autopct='%1.0f%%' if total > 0 else '',
            startangle=90,
            pctdistance=0.75,
            textprops=dict(color="#1f2937", weight="bold", size=8)
        )
        
        # Add center circle to make it a donut
        centre_circle = plt.Circle((0,0), 0.55, fc='white')
        fig.gca().add_artist(centre_circle)
        
        ax.axis('equal')
        plt.tight_layout()
        plt.savefig(output_path, dpi=150, transparent=True)
        plt.close()
        return True
    except Exception as e:
        print(f"Failed to generate matplotlib chart: {str(e)}")
        return False

def generate_pdf_report(contract_id: str, filename: str, analysis: Dict[str, Any], output_path: str) -> str:
    """
    Generates a professional PDF report containing the contract analysis details.
    """
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    
    doc = SimpleDocTemplate(
        output_path,
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=72,
        bottomMargin=72
    )
    
    # Load and customize styles
    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        'CoverTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=28,
        leading=34,
        textColor=PRIMARY_COLOR,
        spaceAfter=15
    )
    
    subtitle_style = ParagraphStyle(
        'CoverSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=12,
        leading=16,
        textColor=colors.HexColor("#4b5563"),
        spaceAfter=30
    )
    
    h1_style = ParagraphStyle(
        'SectionH1',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=18,
        leading=22,
        textColor=PRIMARY_COLOR,
        spaceBefore=15,
        spaceAfter=12,
        keepWithNext=True
    )
    
    h2_style = ParagraphStyle(
        'SectionH2',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=13,
        leading=17,
        textColor=TEXT_COLOR,
        spaceBefore=10,
        spaceAfter=6,
        keepWithNext=True
    )
    
    body_style = ParagraphStyle(
        'ReportBody',
        parent=styles['BodyText'],
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        textColor=TEXT_COLOR,
        spaceAfter=8
    )
    
    bold_body_style = ParagraphStyle(
        'ReportBodyBold',
        parent=body_style,
        fontName='Helvetica-Bold'
    )
    
    disclaimer_style = ParagraphStyle(
        'DisclaimerText',
        parent=styles['Italic'],
        fontName='Helvetica-Oblique',
        fontSize=8,
        leading=11,
        textColor=colors.HexColor("#6b7280"),
        spaceBefore=15
    )
    
    story = []
    
    # ------------------ COVER PAGE ------------------
    story.append(Spacer(1, 1.5 * inch))
    
    # Primary accent block line
    accent_bar = Table([[""]], colWidths=[504], rowHeights=[6])
    accent_bar.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), PRIMARY_COLOR),
        ('BOTTOMPADDING', (0,0), (-1,-1), 0),
        ('TOPPADDING', (0,0), (-1,-1), 0),
    ]))
    story.append(accent_bar)
    story.append(Spacer(1, 15))
    
    story.append(Paragraph("AI CONTRACT ANALYSIS", title_style))
    story.append(Paragraph(f"Comprehensive Legal Risk Audit Report for:<br/><b>{filename}</b>", subtitle_style))
    
    # Risk Score Badge on Cover
    risk_score = analysis.get("risk_score", 0)
    score_color = GREEN_COLOR
    score_lbl = "LOW RISK"
    if risk_score >= 70:
        score_color = RED_COLOR
        score_lbl = "HIGH RISK"
    elif risk_score >= 40:
        score_color = ORANGE_COLOR
        score_lbl = "MEDIUM RISK"
        
    score_table_data = [
        [
            Paragraph("<b>OVERALL RISK SCORE</b>", ParagraphStyle('RiskLbl', parent=body_style, fontSize=11, textColor=colors.white)),
            Paragraph(f"<b>{risk_score}/100</b>", ParagraphStyle('RiskVal', parent=body_style, fontSize=24, leading=26, textColor=colors.white, alignment=2))
        ],
        [
            Paragraph(f"Risk Rating: <b>{score_lbl}</b>", ParagraphStyle('RiskText', parent=body_style, fontSize=10, textColor=colors.white)),
            Paragraph("Generative AI Evaluation", ParagraphStyle('RiskSub', parent=body_style, fontSize=8, textColor=colors.white, alignment=2))
        ]
    ]
    
    score_table = Table(score_table_data, colWidths=[200, 100])
    score_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), score_color),
        ('PADDING', (0,0), (-1,-1), 12),
        ('ALIGN', (1,0), (1,-1), 'RIGHT'),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('BOTTOMPADDING', (0,0), (-1,0), 2),
        ('TOPPADDING', (0,1), (-1,1), 2),
    ]))
    
    story.append(score_table)
    
    # Cover Metadata
    story.append(Spacer(1, 2 * inch))
    metadata_data = [
        [Paragraph("<b>Date Generated:</b>", bold_body_style), Paragraph(datetime.datetime.now().strftime("%B %d, %Y"), body_style)],
        [Paragraph("<b>Document Name:</b>", bold_body_style), Paragraph(filename, body_style)],
        [Paragraph("<b>Contract ID:</b>", bold_body_style), Paragraph(contract_id, body_style)],
    ]
    metadata_table = Table(metadata_data, colWidths=[120, 384])
    metadata_table.setStyle(TableStyle([
        ('BOTTOMPADDING', (0,0), (-1,-1), 4),
        ('TOPPADDING', (0,0), (-1,-1), 4),
        ('LINEBELOW', (0,0), (-1,-1), 0.5, BORDER_COLOR),
    ]))
    story.append(metadata_table)
    
    story.append(PageBreak())
    
    # ------------------ EXECUTIVE SUMMARY ------------------
    story.append(Paragraph("Executive Summary", h1_style))
    summary_text = analysis.get("summary", "No executive summary available.")
    story.append(Paragraph(summary_text, body_style))
    story.append(Spacer(1, 15))
    
    # ------------------ RISK BREAKDOWN ------------------
    story.append(Paragraph("Risk Breakdown & Analysis", h1_style))
    
    # Create matplotlib chart
    chart_filename = f"{contract_id}_risk_chart.png"
    chart_path = os.path.join(os.path.dirname(output_path), chart_filename)
    chart_success = generate_risk_chart(analysis.get("risky_clauses", []), chart_path)
    
    # Count specific risks
    high_count = sum(1 for c in analysis.get("risky_clauses", []) if c.get("risk_level", "").lower() == "high")
    med_count = sum(1 for c in analysis.get("risky_clauses", []) if c.get("risk_level", "").lower() == "medium")
    low_count = sum(1 for c in analysis.get("risky_clauses", []) if c.get("risk_level", "").lower() == "low")
    
    risk_summary_data = [
        [Paragraph("<b>Risk Severity</b>", bold_body_style), Paragraph("<b>Count</b>", bold_body_style), Paragraph("<b>Status</b>", bold_body_style)],
        [Paragraph("<font color='red'><b>High Risk</b></font>", body_style), Paragraph(str(high_count), body_style), Paragraph("Requires immediate review/renegotiation", body_style)],
        [Paragraph("<font color='orange'><b>Medium Risk</b></font>", body_style), Paragraph(str(med_count), body_style), Paragraph("Contains unfavorable/restrictive terms", body_style)],
        [Paragraph("<font color='green'><b>Low Risk</b></font>", body_style), Paragraph(str(low_count), body_style), Paragraph("Standard terms, minor considerations", body_style)]
    ]
    
    risk_tbl = Table(risk_summary_data, colWidths=[100, 50, 204])
    risk_tbl.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), LIGHT_BG),
        ('GRID', (0,0), (-1,-1), 0.5, BORDER_COLOR),
        ('PADDING', (0,0), (-1,-1), 8),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
    ]))
    
    # Layout chart and table side by side if chart was generated
    if chart_success and os.path.exists(chart_path):
        side_table = Table([[Image(chart_path, width=2.0*inch, height=2.0*inch), risk_tbl]], colWidths=[2.2*inch, 4.8*inch])
        side_table.setStyle(TableStyle([
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('BOTTOMPADDING', (0,0), (-1,-1), 0),
            ('TOPPADDING', (0,0), (-1,-1), 0),
            ('LEFTPADDING', (1,0), (1,0), 10),
        ]))
        story.append(side_table)
    else:
        story.append(risk_tbl)
        
    story.append(Spacer(1, 20))
    
    # ------------------ KEY CLAUSES ------------------
    story.append(Paragraph("Key Clauses Identified", h1_style))
    
    key_clauses_data = [
        [
            Paragraph("<b>Clause</b>", bold_body_style),
            Paragraph("<b>Location</b>", bold_body_style),
            Paragraph("<b>Summary & Commercial Meaning</b>", bold_body_style)
        ]
    ]
    
    for kc in analysis.get("key_clauses", []):
        page_val = kc.get("page", "N/A")
        page_str = f"Page {page_val}" if page_val != "N/A" else "N/A"
        key_clauses_data.append([
            Paragraph(f"<b>{kc.get('name', 'Clause')}</b>", body_style),
            Paragraph(page_str, body_style),
            Paragraph(f"<b>Overview:</b> {kc.get('description', '')}<br/><b>Interpretation:</b> {kc.get('interpretation', '')}", body_style)
        ])
        
    key_clauses_table = Table(key_clauses_data, colWidths=[110, 60, 334])
    key_clauses_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), LIGHT_BG),
        ('GRID', (0,0), (-1,-1), 0.5, BORDER_COLOR),
        ('PADDING', (0,0), (-1,-1), 8),
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
    ]))
    story.append(key_clauses_table)
    story.append(Spacer(1, 20))
    
    # ------------------ RISKS & RECOMMENDATIONS ------------------
    story.append(PageBreak())
    story.append(Paragraph("Risky Clauses & Recommendations", h1_style))
    
    risks_list = analysis.get("risky_clauses", [])
    if not risks_list:
        story.append(Paragraph("No risky or unfavorable clauses were detected in this agreement.", body_style))
    else:
        for idx, rc in enumerate(risks_list):
            r_level = rc.get("risk_level", "Low").upper()
            r_color = GREEN_COLOR
            if r_level == "HIGH":
                r_color = RED_COLOR
            elif r_level == "MEDIUM":
                r_color = ORANGE_COLOR
                
            confidence = rc.get("confidence", "N/A")
            confidence_str = f" (Confidence: {confidence}%)" if confidence != "N/A" else ""
            
            page_val = rc.get("page", "N/A")
            page_str = f"Page {page_val}" if page_val != "N/A" else "N/A"
            
            risk_flowable = []
            risk_flowable.append(Paragraph(f"<b>{idx+1}. {rc.get('name', 'Risk Item')}</b>", h2_style))
            
            badge_text = f"<font color='{r_color}'><b>{r_level} RISK</b></font>{confidence_str} | <b>Location:</b> {page_str}"
            risk_flowable.append(Paragraph(badge_text, ParagraphStyle('Badge', parent=body_style, spaceAfter=4)))
            
            desc_text = f"<b>Description:</b> {rc.get('description', '')}"
            risk_flowable.append(Paragraph(desc_text, body_style))
            
            rec_text = f"<b>Recommendation:</b> {rc.get('recommendation', '')}"
            risk_flowable.append(Paragraph(rec_text, ParagraphStyle('Rec', parent=body_style, textColor=PRIMARY_COLOR, fontName='Helvetica-Oblique')))
            
            risk_flowable.append(Spacer(1, 10))
            
            story.append(KeepTogether(risk_flowable))
            
    story.append(Spacer(1, 20))
    
    # ------------------ DISCLAIMER ------------------
    disclaimer_block = []
    disclaimer_block.append(Paragraph("<b>Disclaimer</b>", ParagraphStyle('DiscTitle', parent=bold_body_style, fontSize=9, textColor=colors.HexColor("#4b5563"))))
    disclaimer_block.append(Paragraph(
        "Disclaimer: This AI-generated analysis is for informational purposes only and is not legal advice. "
        "Consult a qualified legal professional before making decisions based on this report.",
        disclaimer_style
    ))
    story.append(KeepTogether(disclaimer_block))
    
    # Build Document
    doc.build(story, canvasmaker=NumberedCanvas)
    
    # Clean up the chart image if it exists
    if chart_success and os.path.exists(chart_path):
        try:
            # We delay removal slightly if needed, but since doc.build is synchronous and finished,
            # we can delete it immediately so there are no temp files laying around.
            os.remove(chart_path)
        except Exception:
            pass
            
    return output_path
